openapi: 3.0.3
info:
  title: API de animales
  description: |
    # Título
    API para animales que permite
    operaciones CRUD con animales.
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Servidor local de pruebas

tags:
- name: animal
  description: Animales

paths:
  /animales:
    get:
      summary: Obtener todos los animales
      description: Obtener istado de todos los animales
      operationId: getAnimales
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/animal'
        default:
          description: Error al buscar animales
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    post:
        tags:
          - animal
        summary: Crear un nuevo animal
        description: Crear animal
        operationId: createAnimal
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/animal'
        responses:

          '201':
            description: Animal creado con éxito
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/info_nuevo_animal'
          default:
            description: Error al crear el evento
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/error'

    /animales/search:
      get:
        summary: Buscar animales por hábitat
        parameters:
          - in: query
            name: habitat
            required: true
            schema:
              type: string
            description: Hábitat para filtrar los animales
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/animal'
    /animales/pagina:
      get:
        summary: Obtener animales paginados
        parameters:
          - in: query
            name: page
            schema:
              type: integer
            description: Número de página solicitada
          - in: query
            name: pageSize
            schema:
              type: integer
            description: Tamaño de página (número de resultados por página)
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    page:
                      type: integer
                      description: Número de página actual
                    pageSize:
                      type: integer
                      description: Tamaño de página
                    totalCount:
                      type: integer
                      description: Total de resultados
                    totalPages:
                      type: integer
                      description: Total de páginas
                    results:
                      type: array
                      items:
                        $ref: '#/components/schemas/animal'
          '400':
            description: No hay contenido
            content:
              application/json:
                schema:
                  type: string

    /animales/{id}:
      put:
        summary: Actualizar un animal por ID
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: integer
            description: ID del animal a actualizar
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/animal_editado'
        responses:
          '200':
            description: Modificado correctamente
          '400':
            description: No modificado
        get:
          summary: Obtener un animal por ID
          parameters:
            - in: path
              name: id
              required: true
              schema:
                type: integer
              description: ID del animal a buscar
          responses:
            '200':
              description: OK
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/animal'
            '404':
              description: Animal no encontrado
        delete:
          summary: Eliminar un animal por ID
          parameters:
            - in: path
              name: id
              required: true
              schema:
                type: integer
              description: ID del animal a eliminar
          responses:
            '200':
              description: Borrado correctamente
            '400':
              description: No ha sido borrado
            '404':
              description: Animal no encontrado
    /animales/filter-peso/{valor}:
      get:
        summary: Filtrar animales por peso mayor a un valor específico
        parameters:
          - in: path
            name: valor
            required: true
            schema:
              type: integer
            description: Valor para filtrar los animales por peso
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/animal'
    /especies:
      get:
        summary: Obtener todas las especies
        responses:
          '200':
            description: Respuesta exitosa
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/especie'
          '404':
            description: Error al buscar especies
            content:
              application/xml:
                schema:
                  type: string
        /{id}:
          get:
            summary: Obtener una especie por su ID
            parameters:
              - name: id
                in: path
                description: ID de la especie
                required: true
                schema:
                  type: integer
            responses:
              '200':
                description: Respuesta exitosa
                content:
                  application/json:
                    schema:
                     $ref: '#/components/schemas/especie'
              '404':
                description: Error al acceder a la especie
                content:
                  application/xml:
                    schema:
                      type: string
    put:
      tags:
        - especie
      summary: Modificar información de una especie concreta
      description: Modificar especie
      operationId: updateEspecie
      parameters:
        - name: id
          in: path
          description: ID de la especie
          required: true
          style: simple
          explode: false
          schema:
            $ref: '#/components/schemas/id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/especie_editada'
      responses:
        "201":
          description: Ok
        default:
          description: Error al acceder a la especie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

      delete:
        tags:
          - especie
        summary: Borrar una especie específica
        description: Borrar especie
        operationId: deleteEspecie
        parameters:
          - name: id
            in: path
            description: ID de la especie
            required: true
            style: simple
            explode: false
            schema:
              $ref: '#/components/schemas/id'
        responses:
          "200":
            description: Ok
          default:
            description: Error al acceder a la  especie
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/error'

  /lugares:
    get:
      summary: Obtener todos los lugares
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/lugar'
        default:
          description: Error al buscar animales
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    post:
        summary: Crear un nuevo lugar
        description: Crear lugar
        operationId: createLugar
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lugar_editada'
        responses:
          '201':
            description: Lugar creado con éxito
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/info_nuevo_lugar'
          default:
            description: Error al crear el evento
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/error'
  /lugares/{id}:
    get:
      tags:
      - lugar
      summary: Obtener información de un lugar concreto
      description: Obtener info
      operationId: getLugar
      parameters:
      - name: id
        in: path
        description: ID del lugar
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/id'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lugar'
            application/xml:
              schema:
                $ref: '#/components/schemas/lugar'
        '404':
          description: Lugar no encontrado
          content:
            application/json:
              schema:
                type: string


    put:
      tags:
        - lugar
      summary: Modificar información de un lugar concreto
      description: Modificar lugar
      operationId: updateLugar
      parameters:
        - name: id
          in: path
          description: ID del lugar
          required: true
          style: simple
          explode: false
          schema:
            $ref: '#/components/schemas/id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/lugar_editado'
      responses:
        '204':
          description: No Content
        default:
            description: Error al actualizar la información del lugar
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/error'

    delete:
      tags:
        - lugar
      summary: Borrar un lugar específico
      description: Borrar lugar
      operationId: deleteLugar
      parameters:
        - name: id
          in: path
          description: ID del lugar
          required: true
          style: simple
          explode: false
          schema:
            $ref: '#/components/schemas/id'
      responses:
        '200':
          description: Ok
        default:
          description: Error al borrar un lugar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      put:
        tags:
        - animal
        summary: Modificar información de un animal concreto
        description: Modificar animal
        operationId: updateAnimal
        parameters:
        - name: id
          in: path
          description: ID del animal
          required: true
          style: simple
          explode: false
          schema:
            $ref: '#/components/schemas/id'
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/animal_editado'
        responses:
          "201":
            description: Ok
          default:
            description: Error al acceder al animal
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/error'

  /gifs/{keyword}:
    get:
      summary: Obtener GIF por palabra clave
      parameters:
        - name: keyword
          in: path
          required: true
          description: Palabra clave para buscar GIF
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gifs'
        default:
            description: Error al buscar gifs
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/error'

components:
  schemas:
    id:
      minimum: 0
      type: integer

    error:
      type: object
      properties:
        descripcion:
          type: string
        codigo:
          type: integer
      example:
        descripcion: Datos introducidos erroneos
        codigo: 400
    info_nuevo_elemento:
      type: object
      properties:
        _id:
          $ref: '#/components/schemas/id'
      example:
        id: 123
    animales_pagination:
      type: object
      properties:
        page:
          type: integer
        page_size:
          type: integer
        page_count:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/animal'
      example:
        data:
        - _id: 1
          Title: Girafa
          Altura_media: 5,5 metros
          Peso: 850 kg
          Habitat:
          - África
          - Somalia
        - _id: 2
          Title: Girafa
          Altura_media: 5,5 metros
          Peso: 850 kg
          Habitat:
          - África
          - Somalia
        page: 0
        page_count: 2
        page_size: 6
    animal:
      type: object
      properties:
        _id:
          type: integer
          minimum: 0
        Altura_media:
          type: string
          nullable: true
        Peso:
          type: string
        Habitat:
          $ref: '#/components/schemas/habitat'
        Title:
          type: string
      required:
        - _id
        - Altura_media
        - Peso
        - Habitat
        - Title
      example:
          _id: 1
          Title: Girafa
          Altura_media: 5,5 metros
          Peso: 850 kg
          Habitat:
          - África
          - Somalia
    especie:
      type: object
      properties:
          id:
            type: integer
          tipo:
            type: string
          descripcion:
            type: string
            nullable: true
          required:
          - id
          - tipo
          example:
            id: 4
            tipo: Reptil
            descripcion: Los reptiles son animales vertebrados que se caracterizan por tener escamas en su piel y por ser de sangre fría, como las serpientes y los cocodrilos.

    nuevo:
      type: object
      properties:
          _id:
            type: integer
            minimum: 0
          Altura_media:
            type: string
            nullable: true
          Peso:
            type: string
          Habitat:
            $ref: '#/components/schemas/habitat'
          Title:
            type: string
          required:
          - _id
          - Altura_media
          - Peso
          - Habitat
          - Title
          example:
          - _id: 2
            Title: Hipopótamo
            Altura_media: 1,5 metros
            Peso: 4000 kg
            Habitat:
              - África Central
    nuevos:
      type: array
      items:
        $ref: '#components/schemas/nuevo'
    animal_editado:
      type: object
      properties:
        Title:
          type: string
        Altura_media:
          type: string
          nullable: true
        Peso:
          type: string
        Habitat:
          $ref: '#/components/schemas/habitat'
      required:
        - Title
        - Altura_media
        - Peso
        - Habitat

      example:
        - _id: 1
          Title: Girafa
          Altura_media: 5,5 metros
          Peso: 850 kg
          Habitat:
          - África
          - Somalia
    lugar:
      type: object
      properties:
          id:
            type: integer
          nombre:
            type: string
          ubicacion:
            type: string
          animales:
            type: array
            items:
              type: string
          clima:
            type: string
          superficie:
            type: number
          visitantes_anuales:
            type: number
          required:
            - id
            - nombre
            - ubicacion
            - animales
            - clima
            - superficie
            - visitantes_anuales
    lugar_editado:
      type: object
      properties:
        Nombre:
          type: string
        Ubicacion:
          type: string
        Animales:
          type: array
        Clima:
          type: string
        Superficie:
          type: number
        Visitantes_anuales:
          type: number
      required:
        - Nombre
        - Ubicacion
        - Animales
        - Clima
        - Superficie
        - Visitantes_anuales
    especie_editada:
      type: object
      properties:
        Nombre:
          type: string
        Tipo:
          type: string
        Descripcion:
          type: string
      required:
        - Nombre
        - Tipo
        - Descripcion
      example:
        id: 5
        nombre: Pez
        descripcion: Los peces son animales acuáticos que tienen branquias para respirar bajo el agua y se caracterizan por tener aletas y escamas en su cuerpo.

    habitat:
      type: object
      properties:
        array:
          type: array
        items:
          $ref: '#/components/schemas/habitat'
      xml:
        wrapped: true
      string:
        type: string
        example: Somalia

  parameters:
    id:
      name: id
      in: path
      description: ID del animal
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/id'
    habitat:
      name: habitat
      in: query
      description: Nombre del habitat
      required: true
      style: form
      explode: true
      schema:
        $ref: '#/components/schemas/lugar'
    page:
      name: page
      in: query
      description: pagina solicitada
      required: false
      style: form
      explode: false
      schema:
        minimum: 1
        type: integer
    page_size:
      name: page_size
      in: query
      description: Cantidad de animales solicitados
      required: false
      style: form
      explode: false
      schema:
        minimum: 1
        type: integer
    search:
      name: search
      in: query
      description: animal a buscar
      required: false
      style: form
      explode: true
      schema:
        type: string
